from collections import defaultdict
graph = defaultdict(dict)
graph['Corvisart']['Glacière'] = 60.0
graph['Corvisart']["Place d'Italie"] = 60.0
graph['Glacière']['Corvisart'] = 60.0
graph['Glacière']['Saint-Jacques'] = 60.0
graph['Saint-Jacques']['Glacière'] = 60.0
graph['Saint-Jacques']['Denfert-Rochereau'] = 60.0
graph['Denfert-Rochereau']['Saint-Jacques'] = 60.0
graph['Denfert-Rochereau']['Raspail'] = 60.0
graph['Denfert-Rochereau']['Mouton-Duvernet'] = 60.0
graph['Raspail']['Denfert-Rochereau'] = 60.0
graph['Raspail']['Edgar Quinet'] = 60.0
graph['Raspail']['Vavin'] = 60.0
graph['Edgar Quinet']['Raspail'] = 60.0
graph['Edgar Quinet']['Montparnasse Bienvenue'] = 60.0
graph['Montparnasse Bienvenue']['Edgar Quinet'] = 60.0
graph['Montparnasse Bienvenue']['Pasteur'] = 60.0
graph['Montparnasse Bienvenue']['Falguière'] = 60.0
graph['Montparnasse Bienvenue']['Notre-Dame des Champs'] = 60.0
graph['Montparnasse Bienvenue']['Duroc'] = 60.0
graph['Montparnasse Bienvenue']['Gaîté'] = 60.0
graph['Montparnasse Bienvenue']['Saint-Placide'] = 60.0
graph['Montparnasse Bienvenue']['Vavin'] = 60.0
graph['Pasteur']['Montparnasse Bienvenue'] = 60.0
graph['Pasteur']['Sèvres-Lecourbe'] = 60.0
graph['Pasteur']['Volontaires'] = 60.0
graph['Pasteur']['Falguière'] = 60.0
graph['Sèvres-Lecourbe']['Pasteur'] = 60.0
graph['Sèvres-Lecourbe']['Cambronne'] = 60.0
graph['Cambronne']['Sèvres-Lecourbe'] = 60.0
graph['Cambronne']['La Motte-Picquet - Grenelle'] = 60.0
graph['La Motte-Picquet - Grenelle']['Cambronne'] = 60.0
graph['La Motte-Picquet - Grenelle']['Dupleix'] = 60.0
graph['La Motte-Picquet - Grenelle']['Avenue Émile Zola'] = 60.0
graph['La Motte-Picquet - Grenelle']['Ségur'] = 60.0
graph['La Motte-Picquet - Grenelle']['Commerce'] = 60.0
graph['La Motte-Picquet - Grenelle']['École Militaire'] = 60.0
graph['Dupleix']['La Motte-Picquet - Grenelle'] = 60.0
graph['Dupleix']['Bir-Hakeim'] = 60.0
graph['Bir-Hakeim']['Dupleix'] = 60.0
graph['Bir-Hakeim']['Passy'] = 60.0
graph['Passy']['Bir-Hakeim'] = 60.0
graph['Passy']['Trocadéro'] = 60.0
graph['Trocadéro']['Passy'] = 60.0
graph['Trocadéro']['Boissière'] = 60.0
graph['Trocadéro']['Iéna'] = 60.0
graph['Trocadéro']['Rue de la Pompe'] = 60.0
graph['Boissière']['Trocadéro'] = 60.0
graph['Boissière']['Kléber'] = 60.0
graph['Kléber']['Boissière'] = 60.0
graph['Kléber']['Charles de Gaulle - Etoile'] = 120.0
graph['Charles de Gaulle - Etoile']['Kléber'] = 120.0
graph['Charles de Gaulle - Etoile']['Argentine'] = 60.0
graph['Charles de Gaulle - Etoile']['George V'] = 60.0
graph['Charles de Gaulle - Etoile']['Ternes'] = 60.0
graph['Charles de Gaulle - Etoile']['Victor Hugo'] = 60.0
graph['Porte de la Villette']['Aubervilliers-Pantin Quatre Chemins'] = 60.0
graph['Porte de la Villette']['Corentin Cariou'] = 60.0
graph['Aubervilliers-Pantin Quatre Chemins']['Porte de la Villette'] = 60.0
graph['Aubervilliers-Pantin Quatre Chemins']["Fort d'Aubervilliers"] = 120.0
graph["Fort d'Aubervilliers"]['Aubervilliers-Pantin Quatre Chemins'] = 120.0
graph["Fort d'Aubervilliers"]['La Courneuve - 8 Mai 1945'] = 60.0
graph['La Courneuve - 8 Mai 1945']["Fort d'Aubervilliers"] = 60.0
graph['Corentin Cariou']['Porte de la Villette'] = 60.0
graph['Corentin Cariou']['Crimée'] = 60.0
graph['Crimée']['Corentin Cariou'] = 60.0
graph['Crimée']['Riquet'] = 60.0
graph['Riquet']['Crimée'] = 60.0
graph['Riquet']['Stalingrad'] = 60.0
graph['Stalingrad']['Riquet'] = 60.0
graph['Stalingrad']['Louis Blanc'] = 60.0
graph['Stalingrad']['Gare du Nord'] = 120.0
graph['Stalingrad']['Jaurès'] = 60.0
graph['Stalingrad']['La Chapelle'] = 60.0
graph['Louis Blanc']['Stalingrad'] = 60.0
graph['Louis Blanc']['Château Landon'] = 60.0
graph['Louis Blanc']['Jaurès'] = 60.0
graph['Château Landon']['Louis Blanc'] = 60.0
graph['Château Landon']["Gare de l'Est"] = 60.0
graph["Gare de l'Est"]['Château Landon'] = 60.0
graph["Gare de l'Est"]['Poissonnière'] = 60.0
graph["Gare de l'Est"]['Jacques Bonsergent'] = 60.0
graph["Gare de l'Est"]['Gare du Nord'] = 60.0
graph["Gare de l'Est"]["Château d'Eau"] = 60.0
graph['Poissonnière']["Gare de l'Est"] = 60.0
graph['Poissonnière']['Cadet'] = 60.0
graph['Cadet']['Poissonnière'] = 60.0
graph['Cadet']['Le Peletier'] = 60.0
graph['Le Peletier']['Cadet'] = 60.0
graph['Le Peletier']["Chaussée d'Antin - La Fayette"] = 60.0
graph["Chaussée d'Antin - La Fayette"]['Le Peletier'] = 60.0
graph["Chaussée d'Antin - La Fayette"]['Opéra'] = 60.0
graph["Chaussée d'Antin - La Fayette"]['Richelieu - Drouot'] = 60.0
graph["Chaussée d'Antin - La Fayette"]['Havre-Caumartin'] = 60.0
graph['Opéra']["Chaussée d'Antin - La Fayette"] = 60.0
graph['Opéra']['Pyramides'] = 60.0
graph['Opéra']['Quatre Septembre'] = 60.0
graph['Opéra']['Havre-Caumartin'] = 60.0
graph['Opéra']['Madeleine'] = 60.0
graph['Opéra']['Richelieu - Drouot'] = 60.0
graph['Pyramides']['Opéra'] = 60.0
graph['Pyramides']['Palais Royal - Musée du Louvre'] = 60.0
graph['Pyramides']['Châtelet'] = 60.0
graph['Pyramides']['Madeleine'] = 60.0
graph['Palais Royal - Musée du Louvre']['Pyramides'] = 60.0
graph['Palais Royal - Musée du Louvre']['Pont Neuf'] = 60.0
graph['Palais Royal - Musée du Louvre']['Tuileries'] = 60.0
graph['Palais Royal - Musée du Louvre']['Louvre - Rivoli'] = 60.0
graph['Pont Neuf']['Palais Royal - Musée du Louvre'] = 60.0
graph['Pont Neuf']['Châtelet'] = 60.0
graph['Châtelet']['Pont Neuf'] = 60.0
graph['Châtelet']['Pont Marie (Cité des Arts)'] = 60.0
graph['Châtelet']['Louvre - Rivoli'] = 60.0
graph['Châtelet']['Hôtel de Ville'] = 60.0
graph['Châtelet']['Gare de Lyon'] = 180.0
graph['Châtelet']['Pyramides'] = 60.0
graph['Châtelet']['Les Halles'] = 60.0
graph['Châtelet']['Cité'] = 60.0
graph['Pont Marie (Cité des Arts)']['Châtelet'] = 60.0
graph['Pont Marie (Cité des Arts)']['Sully - Morland'] = 60.0
graph['Sully - Morland']['Pont Marie (Cité des Arts)'] = 60.0
graph['Sully - Morland']['Jussieu'] = 60.0
graph['Jussieu']['Sully - Morland'] = 60.0
graph['Jussieu']['Place Monge'] = 60.0
graph['Jussieu']['Cardinal Lemoine'] = 60.0
graph['Jussieu']["Gare d'Austerlitz"] = 120.0
graph['Place Monge']['Jussieu'] = 60.0
graph['Place Monge']['Censier - Daubenton'] = 60.0
graph['Censier - Daubenton']['Place Monge'] = 60.0
graph['Censier - Daubenton']['Les Gobelins'] = 60.0
graph['Les Gobelins']['Censier - Daubenton'] = 60.0
graph['Les Gobelins']["Place d'Italie"] = 60.0
graph["Place d'Italie"]['Les Gobelins'] = 60.0
graph["Place d'Italie"]['Tolbiac'] = 60.0
graph["Place d'Italie"]['Campo-Formio'] = 120.0
graph["Place d'Italie"]['Nationale'] = 60.0
graph["Place d'Italie"]['Corvisart'] = 60.0
graph['Tolbiac']["Place d'Italie"] = 60.0
graph['Tolbiac']['Maison Blanche'] = 60.0
graph['Maison Blanche']['Tolbiac'] = 60.0
graph['Maison Blanche']['Le Kremlin-Bicêtre'] = 120.0
graph['Maison Blanche']["Porte d'Italie"] = 60.0
graph['Le Kremlin-Bicêtre']['Maison Blanche'] = 120.0
graph['Le Kremlin-Bicêtre']['Villejuif Léo Lagrange'] = 60.0
graph['Villejuif Léo Lagrange']['Le Kremlin-Bicêtre'] = 60.0
graph['Villejuif Léo Lagrange']['Villejuif Paul Vaillant-Couturier'] = 60.0
graph['Villejuif Paul Vaillant-Couturier']['Villejuif Léo Lagrange'] = 60.0
graph['Villejuif Paul Vaillant-Couturier']['Villejuif - Louis Aragon'] = 180.0
graph['Villejuif - Louis Aragon']['Villejuif Paul Vaillant-Couturier'] = 180.0
graph['Porte de Saint-Cloud']['Marcel Sembat'] = 120.0
graph['Porte de Saint-Cloud']['Exelmans'] = 60.0
graph['Marcel Sembat']['Porte de Saint-Cloud'] = 120.0
graph['Marcel Sembat']['Billancourt'] = 60.0
graph['Billancourt']['Marcel Sembat'] = 60.0
graph['Billancourt']['Pont de Sèvres'] = 60.0
graph['Pont de Sèvres']['Billancourt'] = 60.0
graph['Porte de Montreuil']['Robespierre'] = 120.0
graph['Porte de Montreuil']['Maraîchers'] = 60.0
graph['Robespierre']['Porte de Montreuil'] = 120.0
graph['Robespierre']['Croix de Chavaux'] = 60.0
graph['Croix de Chavaux']['Robespierre'] = 60.0
graph['Croix de Chavaux']['Mairie de Montreuil'] = 60.0
graph['Mairie de Montreuil']['Croix de Chavaux'] = 60.0
graph['Campo-Formio']["Place d'Italie"] = 120.0
graph['Campo-Formio']['Saint-Marcel'] = 60.0
graph['Saint-Marcel']['Campo-Formio'] = 60.0
graph['Saint-Marcel']["Gare d'Austerlitz"] = 60.0
graph["Gare d'Austerlitz"]['Saint-Marcel'] = 60.0
graph["Gare d'Austerlitz"]['Quai de la Rapée'] = 60.0
graph["Gare d'Austerlitz"]['Jussieu'] = 120.0
graph['Quai de la Rapée']["Gare d'Austerlitz"] = 60.0
graph['Quai de la Rapée']['Bastille'] = 60.0
graph['Bastille']['Quai de la Rapée'] = 60.0
graph['Bastille']['Bréguet-Sabin'] = 60.0
graph['Bastille']['Chemin Vert'] = 60.0
graph['Bastille']['Ledru-Rollin'] = 60.0
graph['Bastille']['Saint-Paul (Le Marais)'] = 120.0
graph['Bastille']['Gare de Lyon'] = 120.0
graph['Bréguet-Sabin']['Bastille'] = 60.0
graph['Bréguet-Sabin']['Richard-Lenoir'] = 60.0
graph['Richard-Lenoir']['Bréguet-Sabin'] = 60.0
graph['Richard-Lenoir']['Oberkampf'] = 60.0
graph['Oberkampf']['Richard-Lenoir'] = 60.0
graph['Oberkampf']['République'] = 60.0
graph['Oberkampf']['Saint-Ambroise'] = 60.0
graph['République']['Oberkampf'] = 60.0
graph['République']['Jacques Bonsergent'] = 60.0
graph['République']['Parmentier'] = 60.0
graph['République']['Temple'] = 60.0
graph['République']['Strasbourg - Saint-Denis'] = 60.0
graph['République']['Filles du Calvaire'] = 60.0
graph['République']['Arts et Métiers'] = 60.0
graph['République']['Goncourt'] = 60.0
graph['Jacques Bonsergent']['République'] = 60.0
graph['Jacques Bonsergent']["Gare de l'Est"] = 60.0
graph['Gare du Nord']["Gare de l'Est"] = 60.0
graph['Gare du Nord']['Stalingrad'] = 120.0
graph['Gare du Nord']['Barbès - Rochechouart'] = 120.0
graph['Jaurès']['Stalingrad'] = 60.0
graph['Jaurès']['Laumière'] = 60.0
graph['Jaurès']['Bolivar'] = 60.0
graph['Jaurès']['Louis Blanc'] = 60.0
graph['Jaurès']['Colonel Fabien'] = 60.0
graph['Laumière']['Jaurès'] = 60.0
graph['Laumière']['Ourcq'] = 60.0
graph['Ourcq']['Laumière'] = 60.0
graph['Ourcq']['Porte de Pantin'] = 60.0
graph['Porte de Pantin']['Ourcq'] = 60.0
graph['Porte de Pantin']['Hoche'] = 60.0
graph['Hoche']['Porte de Pantin'] = 60.0
graph['Hoche']['Église de Pantin'] = 60.0
graph['Église de Pantin']['Hoche'] = 60.0
graph['Église de Pantin']['Bobigny-Pantin - Raymond Queneau'] = 60.0
graph['Bobigny-Pantin - Raymond Queneau']['Église de Pantin'] = 60.0
graph['Bobigny-Pantin - Raymond Queneau']['Bobigny Pablo Picasso'] = 180.0
graph['Bobigny Pablo Picasso']['Bobigny-Pantin - Raymond Queneau'] = 180.0
graph['Gambetta']['Père Lachaise'] = 60.0
graph['Gambetta']['Porte de Bagnolet'] = 60.0
graph['Gambetta']['Pelleport'] = 60.0
graph['Père Lachaise']['Gambetta'] = 60.0
graph['Père Lachaise']['Rue Saint-Maur'] = 60.0
graph['Père Lachaise']['Philippe Auguste'] = 60.0
graph['Père Lachaise']['Ménilmontant'] = 60.0
graph['Rue Saint-Maur']['Père Lachaise'] = 60.0
graph['Rue Saint-Maur']['Parmentier'] = 60.0
graph['Parmentier']['Rue Saint-Maur'] = 60.0
graph['Parmentier']['République'] = 60.0
graph['Temple']['République'] = 60.0
graph['Temple']['Arts et Métiers'] = 60.0
graph['Arts et Métiers']['Temple'] = 60.0
graph['Arts et Métiers']['Réaumur - Sébastopol'] = 60.0
graph['Arts et Métiers']['Rambuteau'] = 60.0
graph['Arts et Métiers']['République'] = 60.0
graph['Réaumur - Sébastopol']['Arts et Métiers'] = 60.0
graph['Réaumur - Sébastopol']['Sentier'] = 60.0
graph['Réaumur - Sébastopol']['Strasbourg - Saint-Denis'] = 60.0
graph['Réaumur - Sébastopol']['Etienne Marcel'] = 60.0
graph['Sentier']['Réaumur - Sébastopol'] = 60.0
graph['Sentier']['Bourse'] = 60.0
graph['Bourse']['Sentier'] = 60.0
graph['Bourse']['Quatre Septembre'] = 60.0
graph['Quatre Septembre']['Bourse'] = 60.0
graph['Quatre Septembre']['Opéra'] = 60.0
graph['Havre-Caumartin']['Opéra'] = 60.0
graph['Havre-Caumartin']['Saint-Lazare'] = 60.0
graph['Havre-Caumartin']["Chaussée d'Antin - La Fayette"] = 60.0
graph['Havre-Caumartin']['Saint-Augustin'] = 60.0
graph['Saint-Lazare']['Havre-Caumartin'] = 60.0
graph['Saint-Lazare']['Europe'] = 60.0
graph['Saint-Lazare']['Madeleine'] = 60.0
graph['Saint-Lazare']["Trinité - d'Estienne d'Orves"] = 60.0
graph['Saint-Lazare']['Liège'] = 60.0
graph['Saint-Lazare']['Miromesnil'] = 120.0
graph['Saint-Lazare']['Pont Cardinet'] = 120.0
graph['Europe']['Saint-Lazare'] = 60.0
graph['Europe']['Villiers'] = 60.0
graph['Villiers']['Europe'] = 60.0
graph['Villiers']['Malesherbes'] = 60.0
graph['Villiers']['Rome'] = 60.0
graph['Villiers']['Monceau'] = 60.0
graph['Malesherbes']['Villiers'] = 60.0
graph['Malesherbes']['Wagram'] = 60.0
graph['Wagram']['Malesherbes'] = 60.0
graph['Wagram']['Pereire'] = 60.0
graph['Pereire']['Wagram'] = 60.0
graph['Pereire']['Porte de Champerret'] = 60.0
graph['Porte de Champerret']['Pereire'] = 60.0
graph['Porte de Champerret']['Louise Michel'] = 60.0
graph['Louise Michel']['Porte de Champerret'] = 60.0
graph['Louise Michel']['Anatole France'] = 60.0
graph['Anatole France']['Louise Michel'] = 60.0
graph['Anatole France']['Pont de Levallois - Bécon'] = 60.0
graph['Pont de Levallois - Bécon']['Anatole France'] = 60.0
graph['Porte de Bagnolet']['Gambetta'] = 60.0
graph['Porte de Bagnolet']['Gallieni'] = 60.0
graph['Gallieni']['Porte de Bagnolet'] = 60.0
graph["Porte d'Auteuil"]['Michel-Ange - Molitor'] = 120.0
graph["Porte d'Auteuil"]['Michel-Ange - Auteuil'] = 60.0
graph["Porte d'Auteuil"]['Boulogne Jean Jaurès'] = 120.0
graph['Michel-Ange - Molitor']["Porte d'Auteuil"] = 120.0
graph['Michel-Ange - Molitor']['Chardon Lagache'] = 60.0
graph['Michel-Ange - Molitor']['Boulogne Jean Jaurès'] = 120.0
graph['Michel-Ange - Molitor']['Michel-Ange - Auteuil'] = 60.0
graph['Michel-Ange - Molitor']['Exelmans'] = 60.0
graph['Chardon Lagache']['Michel-Ange - Molitor'] = 60.0
graph['Chardon Lagache']['Mirabeau'] = 60.0
graph['Mirabeau']['Chardon Lagache'] = 60.0
graph['Mirabeau']['Javel - André Citroën'] = 60.0
graph['Javel - André Citroën']['Mirabeau'] = 60.0
graph['Javel - André Citroën']['Charles Michels'] = 60.0
graph['Javel - André Citroën']["Église d'Auteuil"] = 60.0
graph['Charles Michels']['Javel - André Citroën'] = 60.0
graph['Charles Michels']['Avenue Émile Zola'] = 60.0
graph['Avenue Émile Zola']['Charles Michels'] = 60.0
graph['Avenue Émile Zola']['La Motte-Picquet - Grenelle'] = 60.0
graph['Ségur']['La Motte-Picquet - Grenelle'] = 60.0
graph['Ségur']['Duroc'] = 60.0
graph['Duroc']['Ségur'] = 60.0
graph['Duroc']['Vaneau'] = 60.0
graph['Duroc']['Saint-François-Xavier'] = 60.0
graph['Duroc']['Montparnasse Bienvenue'] = 60.0
graph['Vaneau']['Duroc'] = 60.0
graph['Vaneau']['Sèvres - Babylone'] = 60.0
graph['Sèvres - Babylone']['Vaneau'] = 60.0
graph['Sèvres - Babylone']['Mabillon'] = 60.0
graph['Sèvres - Babylone']['Rennes'] = 60.0
graph['Sèvres - Babylone']['Rue du Bac'] = 60.0
graph['Mabillon']['Sèvres - Babylone'] = 60.0
graph['Mabillon']['Odéon'] = 60.0
graph['Odéon']['Mabillon'] = 60.0
graph['Odéon']['Cluny - La Sorbonne'] = 60.0
graph['Odéon']['Saint-Michel'] = 60.0
graph['Odéon']['Saint-Germain-des-Prés'] = 60.0
graph['Cluny - La Sorbonne']['Odéon'] = 60.0
graph['Cluny - La Sorbonne']['Maubert - Mutualité'] = 60.0
graph['Maubert - Mutualité']['Cluny - La Sorbonne'] = 60.0
graph['Maubert - Mutualité']['Cardinal Lemoine'] = 60.0
graph['Cardinal Lemoine']['Maubert - Mutualité'] = 60.0
graph['Cardinal Lemoine']['Jussieu'] = 60.0
graph["Église d'Auteuil"]['Javel - André Citroën'] = 60.0
graph["Église d'Auteuil"]['Michel-Ange - Auteuil'] = 60.0
graph['Michel-Ange - Auteuil']["Église d'Auteuil"] = 60.0
graph['Michel-Ange - Auteuil']["Porte d'Auteuil"] = 60.0
graph['Michel-Ange - Auteuil']['Jasmin'] = 60.0
graph['Michel-Ange - Auteuil']['Michel-Ange - Molitor'] = 60.0
graph['Boulogne Jean Jaurès']["Porte d'Auteuil"] = 120.0
graph['Boulogne Jean Jaurès']['Boulogne Pont de Saint-Cloud'] = 120.0
graph['Boulogne Jean Jaurès']['Michel-Ange - Molitor'] = 120.0
graph['Boulogne Pont de Saint-Cloud']['Boulogne Jean Jaurès'] = 120.0
graph['Porte des Lilas']['Saint-Fargeau'] = 60.0
graph['Porte des Lilas']['Télégraphe'] = 60.0
graph['Porte des Lilas']['Mairie des Lilas'] = 60.0
graph['Saint-Fargeau']['Porte des Lilas'] = 60.0
graph['Saint-Fargeau']['Pelleport'] = 60.0
graph['Pelleport']['Saint-Fargeau'] = 60.0
graph['Pelleport']['Gambetta'] = 60.0
graph['Pré-Saint-Gervais']['Danube'] = 60.0
graph['Pré-Saint-Gervais']['Place des Fêtes'] = 120.0
graph['Danube']['Pré-Saint-Gervais'] = 60.0
graph['Danube']['Botzaris'] = 60.0
graph['Botzaris']['Danube'] = 60.0
graph['Botzaris']['Buttes Chaumont'] = 60.0
graph['Botzaris']['Place des Fêtes'] = 60.0
graph['Buttes Chaumont']['Botzaris'] = 60.0
graph['Buttes Chaumont']['Bolivar'] = 60.0
graph['Bolivar']['Buttes Chaumont'] = 60.0
graph['Bolivar']['Jaurès'] = 60.0
graph['Place des Fêtes']['Botzaris'] = 60.0
graph['Place des Fêtes']['Pré-Saint-Gervais'] = 120.0
graph['Place des Fêtes']['Jourdain'] = 60.0
graph['Place des Fêtes']['Télégraphe'] = 60.0
graph['Porte Maillot']['Les Sablons'] = 60.0
graph['Porte Maillot']['Argentine'] = 60.0
graph['Les Sablons']['Porte Maillot'] = 60.0
graph['Les Sablons']['Pont de Neuilly'] = 60.0
graph['Pont de Neuilly']['Les Sablons'] = 60.0
graph['Pont de Neuilly']['Esplanade de la Défense'] = 60.0
graph['Esplanade de la Défense']['Pont de Neuilly'] = 60.0
graph['Esplanade de la Défense']['La Défense (Grande Arche)'] = 60.0
graph['La Défense (Grande Arche)']['Esplanade de la Défense'] = 60.0
graph['Porte de Versailles']['Corentin Celton'] = 60.0
graph['Porte de Versailles']['Convention'] = 60.0
graph['Corentin Celton']['Porte de Versailles'] = 60.0
graph['Corentin Celton']["Mairie d'Issy"] = 60.0
graph["Mairie d'Issy"]['Corentin Celton'] = 60.0
graph['Convention']['Porte de Versailles'] = 60.0
graph['Convention']['Vaugirard'] = 60.0
graph['Vaugirard']['Convention'] = 60.0
graph['Vaugirard']['Volontaires'] = 60.0
graph['Volontaires']['Vaugirard'] = 60.0
graph['Volontaires']['Pasteur'] = 60.0
graph['Falguière']['Pasteur'] = 60.0
graph['Falguière']['Montparnasse Bienvenue'] = 60.0
graph['Notre-Dame des Champs']['Montparnasse Bienvenue'] = 60.0
graph['Notre-Dame des Champs']['Rennes'] = 60.0
graph['Rennes']['Notre-Dame des Champs'] = 60.0
graph['Rennes']['Sèvres - Babylone'] = 60.0
graph['Rue du Bac']['Sèvres - Babylone'] = 60.0
graph['Rue du Bac']['Solférino'] = 60.0
graph['Solférino']['Rue du Bac'] = 60.0
graph['Solférino']['Assemblée Nationale'] = 60.0
graph['Assemblée Nationale']['Solférino'] = 60.0
graph['Assemblée Nationale']['Concorde'] = 60.0
graph['Concorde']['Assemblée Nationale'] = 60.0
graph['Concorde']['Madeleine'] = 60.0
graph['Concorde']['Invalides'] = 60.0
graph['Concorde']['Champs-Élysées - Clemenceau'] = 60.0
graph['Concorde']['Tuileries'] = 60.0
graph['Madeleine']['Concorde'] = 60.0
graph['Madeleine']['Saint-Lazare'] = 60.0
graph['Madeleine']['Opéra'] = 60.0
graph['Madeleine']['Pyramides'] = 60.0
graph["Trinité - d'Estienne d'Orves"]['Saint-Lazare'] = 60.0
graph["Trinité - d'Estienne d'Orves"]['Notre-Dame-de-Lorette'] = 60.0
graph['Notre-Dame-de-Lorette']["Trinité - d'Estienne d'Orves"] = 60.0
graph['Notre-Dame-de-Lorette']['Saint-Georges'] = 60.0
graph['Saint-Georges']['Notre-Dame-de-Lorette'] = 60.0
graph['Saint-Georges']['Pigalle'] = 60.0
graph['Pigalle']['Saint-Georges'] = 60.0
graph['Pigalle']['Abbesses'] = 60.0
graph['Pigalle']['Anvers'] = 60.0
graph['Pigalle']['Blanche'] = 60.0
graph['Abbesses']['Pigalle'] = 60.0
graph['Abbesses']['Lamarck - Caulaincourt'] = 60.0
graph['Lamarck - Caulaincourt']['Abbesses'] = 60.0
graph['Lamarck - Caulaincourt']['Jules Joffrin'] = 60.0
graph['Jules Joffrin']['Lamarck - Caulaincourt'] = 60.0
graph['Jules Joffrin']['Marcadet - Poissonniers'] = 60.0
graph['Marcadet - Poissonniers']['Jules Joffrin'] = 60.0
graph['Marcadet - Poissonniers']['Marx Dormoy'] = 60.0
graph['Marcadet - Poissonniers']['Simplon'] = 60.0
graph['Marcadet - Poissonniers']['Château Rouge'] = 60.0
graph['Marx Dormoy']['Marcadet - Poissonniers'] = 60.0
graph['Marx Dormoy']['Porte de la Chapelle'] = 60.0
graph['Porte de la Chapelle']['Marx Dormoy'] = 60.0
graph['Porte de la Chapelle']['Front Populaire'] = 120.0
graph['Front Populaire']['Porte de la Chapelle'] = 120.0
graph['Front Populaire']['Aimé Césaire'] = 120.0
graph['Aimé Césaire']['Front Populaire'] = 120.0
graph['Aimé Césaire']["Mairie d'Aubervilliers"] = 60.0
graph["Mairie d'Aubervilliers"]['Aimé Césaire'] = 60.0
graph['Balard']['Lourmel'] = 60.0
graph['Lourmel']['Balard'] = 60.0
graph['Lourmel']['Boucicaut'] = 60.0
graph['Boucicaut']['Lourmel'] = 60.0
graph['Boucicaut']['Félix Faure'] = 60.0
graph['Félix Faure']['Boucicaut'] = 60.0
graph['Félix Faure']['Commerce'] = 60.0
graph['Commerce']['Félix Faure'] = 60.0
graph['Commerce']['La Motte-Picquet - Grenelle'] = 60.0
graph['École Militaire']['La Motte-Picquet - Grenelle'] = 60.0
graph['École Militaire']['La Tour-Maubourg'] = 60.0
graph['La Tour-Maubourg']['École Militaire'] = 60.0
graph['La Tour-Maubourg']['Invalides'] = 60.0
graph['Invalides']['La Tour-Maubourg'] = 60.0
graph['Invalides']['Concorde'] = 60.0
graph['Invalides']['Champs-Élysées - Clemenceau'] = 60.0
graph['Invalides']['Varenne'] = 60.0
graph['Richelieu - Drouot']['Opéra'] = 60.0
graph['Richelieu - Drouot']['Grands Boulevards'] = 60.0
graph['Richelieu - Drouot']["Chaussée d'Antin - La Fayette"] = 60.0
graph['Grands Boulevards']['Richelieu - Drouot'] = 60.0
graph['Grands Boulevards']['Bonne Nouvelle'] = 60.0
graph['Bonne Nouvelle']['Grands Boulevards'] = 60.0
graph['Bonne Nouvelle']['Strasbourg - Saint-Denis'] = 60.0
graph['Strasbourg - Saint-Denis']['Bonne Nouvelle'] = 60.0
graph['Strasbourg - Saint-Denis']['République'] = 60.0
graph['Strasbourg - Saint-Denis']["Château d'Eau"] = 60.0
graph['Strasbourg - Saint-Denis']['Réaumur - Sébastopol'] = 60.0
graph['Filles du Calvaire']['République'] = 60.0
graph['Filles du Calvaire']['Saint-Sébastien - Froissart'] = 60.0
graph['Saint-Sébastien - Froissart']['Filles du Calvaire'] = 60.0
graph['Saint-Sébastien - Froissart']['Chemin Vert'] = 60.0
graph['Chemin Vert']['Saint-Sébastien - Froissart'] = 60.0
graph['Chemin Vert']['Bastille'] = 60.0
graph['Ledru-Rollin']['Bastille'] = 60.0
graph['Ledru-Rollin']['Faidherbe - Chaligny'] = 60.0
graph['Faidherbe - Chaligny']['Ledru-Rollin'] = 60.0
graph['Faidherbe - Chaligny']['Reuilly - Diderot'] = 60.0
graph['Reuilly - Diderot']['Faidherbe - Chaligny'] = 60.0
graph['Reuilly - Diderot']['Montgallet'] = 60.0
graph['Reuilly - Diderot']['Gare de Lyon'] = 60.0
graph['Reuilly - Diderot']['Nation'] = 120.0
graph['Montgallet']['Reuilly - Diderot'] = 60.0
graph['Montgallet']['Daumesnil'] = 60.0
graph['Daumesnil']['Montgallet'] = 60.0
graph['Daumesnil']['Michel Bizot'] = 60.0
graph['Daumesnil']['Bel-Air'] = 60.0
graph['Daumesnil']['Dugommier'] = 60.0
graph['Michel Bizot']['Daumesnil'] = 60.0
graph['Michel Bizot']['Porte Dorée'] = 60.0
graph['Porte Dorée']['Michel Bizot'] = 60.0
graph['Porte Dorée']['Porte de Charenton'] = 60.0
graph['Porte de Charenton']['Porte Dorée'] = 60.0
graph['Porte de Charenton']['Liberté'] = 60.0
graph['Liberté']['Porte de Charenton'] = 60.0
graph['Liberté']['Charenton - Écoles'] = 60.0
graph['Charenton - Écoles']['Liberté'] = 60.0
graph['Charenton - Écoles']['Ecole Vétérinaire de Maisons-Alfort'] = 60.0
graph['Ecole Vétérinaire de Maisons-Alfort']['Charenton - Écoles'] = 60.0
graph['Ecole Vétérinaire de Maisons-Alfort']['Maisons-Alfort - Stade'] = 60.0
graph['Maisons-Alfort - Stade']['Ecole Vétérinaire de Maisons-Alfort'] = 60.0
graph['Maisons-Alfort - Stade']['Maisons-Alfort - Les Juilliottes'] = 60.0
graph['Maisons-Alfort - Les Juilliottes']['Maisons-Alfort - Stade'] = 60.0
graph['Maisons-Alfort - Les Juilliottes']["Créteil - L'Échat"] = 60.0
graph["Créteil - L'Échat"]['Maisons-Alfort - Les Juilliottes'] = 60.0
graph["Créteil - L'Échat"]['Créteil - Université'] = 60.0
graph['Créteil - Université']["Créteil - L'Échat"] = 60.0
graph['Créteil - Université']['Créteil - Préfecture'] = 120.0
graph['Créteil - Préfecture']['Créteil - Université'] = 120.0
graph['Créteil - Préfecture']['Pointe du Lac'] = 120.0
graph['Pointe du Lac']['Créteil - Préfecture'] = 120.0
graph['Carrefour Pleyel']['Saint-Denis - Porte de Paris'] = 120.0
graph['Carrefour Pleyel']['Mairie de Saint-Ouen'] = 120.0
graph['Saint-Denis - Porte de Paris']['Carrefour Pleyel'] = 120.0
graph['Saint-Denis - Porte de Paris']['Basilique de Saint-Denis'] = 60.0
graph['Basilique de Saint-Denis']['Saint-Denis - Porte de Paris'] = 60.0
graph['Basilique de Saint-Denis']['Saint-Denis - Université'] = 120.0
graph['Saint-Denis - Université']['Basilique de Saint-Denis'] = 120.0
graph['Asnières - Gennevilliers Les Courtilles']['Les Agnettes'] = 60.0
graph['Les Agnettes']['Asnières - Gennevilliers Les Courtilles'] = 60.0
graph['Les Agnettes']['Gabriel Péri'] = 60.0
graph['Gabriel Péri']['Les Agnettes'] = 60.0
graph['Gabriel Péri']['Mairie de Clichy'] = 120.0
graph['Mairie de Clichy']['Gabriel Péri'] = 120.0
graph['Mairie de Clichy']['Porte de Clichy'] = 120.0
graph['Porte de Clichy']['Mairie de Clichy'] = 120.0
graph['Porte de Clichy']['Brochant'] = 60.0
graph['Porte de Clichy']['Pont Cardinet'] = 60.0
graph['Porte de Clichy']['Saint-Ouen'] = 120.0
graph['Brochant']['Porte de Clichy'] = 60.0
graph['Brochant']['La Fourche'] = 60.0
graph['La Fourche']['Brochant'] = 60.0
graph['La Fourche']['Place de Clichy'] = 60.0
graph['La Fourche']['Guy Môquet'] = 120.0
graph['Place de Clichy']['La Fourche'] = 60.0
graph['Place de Clichy']['Liège'] = 60.0
graph['Place de Clichy']['Blanche'] = 60.0
graph['Place de Clichy']['Rome'] = 60.0
graph['Liège']['Place de Clichy'] = 60.0
graph['Liège']['Saint-Lazare'] = 60.0
graph['Miromesnil']['Saint-Lazare'] = 120.0
graph['Miromesnil']['Champs-Élysées - Clemenceau'] = 60.0
graph['Miromesnil']['Saint-Augustin'] = 60.0
graph['Miromesnil']['Saint-Philippe du Roule'] = 60.0
graph['Champs-Élysées - Clemenceau']['Miromesnil'] = 60.0
graph['Champs-Élysées - Clemenceau']['Invalides'] = 60.0
graph['Champs-Élysées - Clemenceau']['Franklin D. Roosevelt'] = 60.0
graph['Champs-Élysées - Clemenceau']['Concorde'] = 60.0
graph['Varenne']['Invalides'] = 60.0
graph['Varenne']['Saint-François-Xavier'] = 60.0
graph['Saint-François-Xavier']['Varenne'] = 60.0
graph['Saint-François-Xavier']['Duroc'] = 60.0
graph['Gaîté']['Montparnasse Bienvenue'] = 60.0
graph['Gaîté']['Pernety'] = 60.0
graph['Pernety']['Gaîté'] = 60.0
graph['Pernety']['Plaisance'] = 60.0
graph['Plaisance']['Pernety'] = 60.0
graph['Plaisance']['Porte de Vanves'] = 60.0
graph['Porte de Vanves']['Plaisance'] = 60.0
graph['Porte de Vanves']['Malakoff - Plateau de Vanves'] = 60.0
graph['Malakoff - Plateau de Vanves']['Porte de Vanves'] = 60.0
graph['Malakoff - Plateau de Vanves']['Malakoff - Rue Etienne Dolet'] = 60.0
graph['Malakoff - Rue Etienne Dolet']['Malakoff - Plateau de Vanves'] = 60.0
graph['Malakoff - Rue Etienne Dolet']['Châtillon-Montrouge'] = 60.0
graph['Châtillon-Montrouge']['Malakoff - Rue Etienne Dolet'] = 60.0
graph['Guy Môquet']['La Fourche'] = 120.0
graph['Guy Môquet']['Porte de Saint-Ouen'] = 60.0
graph['Porte de Saint-Ouen']['Guy Môquet'] = 60.0
graph['Porte de Saint-Ouen']['Garibaldi'] = 120.0
graph['Garibaldi']['Porte de Saint-Ouen'] = 120.0
graph['Garibaldi']['Mairie de Saint-Ouen'] = 60.0
graph['Mairie de Saint-Ouen']['Garibaldi'] = 60.0
graph['Mairie de Saint-Ouen']['Carrefour Pleyel'] = 120.0
graph['Mairie de Saint-Ouen']['Saint-Ouen'] = 60.0
graph['Argentine']['Porte Maillot'] = 60.0
graph['Argentine']['Charles de Gaulle - Etoile'] = 60.0
graph['George V']['Charles de Gaulle - Etoile'] = 60.0
graph['George V']['Franklin D. Roosevelt'] = 60.0
graph['Franklin D. Roosevelt']['George V'] = 60.0
graph['Franklin D. Roosevelt']['Champs-Élysées - Clemenceau'] = 60.0
graph['Franklin D. Roosevelt']['Saint-Philippe du Roule'] = 60.0
graph['Franklin D. Roosevelt']['Alma - Marceau'] = 60.0
graph['Tuileries']['Concorde'] = 60.0
graph['Tuileries']['Palais Royal - Musée du Louvre'] = 60.0
graph['Louvre - Rivoli']['Palais Royal - Musée du Louvre'] = 60.0
graph['Louvre - Rivoli']['Châtelet'] = 60.0
graph['Hôtel de Ville']['Châtelet'] = 60.0
graph['Hôtel de Ville']['Saint-Paul (Le Marais)'] = 60.0
graph['Hôtel de Ville']['Rambuteau'] = 60.0
graph['Saint-Paul (Le Marais)']['Hôtel de Ville'] = 60.0
graph['Saint-Paul (Le Marais)']['Bastille'] = 120.0
graph['Gare de Lyon']['Bastille'] = 120.0
graph['Gare de Lyon']['Reuilly - Diderot'] = 60.0
graph['Gare de Lyon']['Châtelet'] = 180.0
graph['Gare de Lyon']['Bercy'] = 60.0
graph['Nation']['Reuilly - Diderot'] = 120.0
graph['Nation']['Porte de Vincennes'] = 60.0
graph['Nation']['Avron'] = 60.0
graph['Nation']['Buzenval'] = 60.0
graph['Nation']['Rue des Boulets'] = 60.0
graph['Nation']['Picpus'] = 60.0
graph['Porte de Vincennes']['Nation'] = 60.0
graph['Porte de Vincennes']['Saint-Mandé'] = 60.0
graph['Saint-Mandé']['Porte de Vincennes'] = 60.0
graph['Saint-Mandé']['Bérault'] = 60.0
graph['Bérault']['Saint-Mandé'] = 60.0
graph['Bérault']['Château de Vincennes'] = 60.0
graph['Château de Vincennes']['Bérault'] = 60.0
graph["Mairie d'Ivry"]['Pierre et Marie Curie'] = 60.0
graph['Pierre et Marie Curie']["Mairie d'Ivry"] = 60.0
graph['Pierre et Marie Curie']["Porte d'Ivry"] = 120.0
graph["Porte d'Ivry"]['Pierre et Marie Curie'] = 120.0
graph["Porte d'Ivry"]['Porte de Choisy'] = 60.0
graph['Porte de Choisy']["Porte d'Ivry"] = 60.0
graph['Porte de Choisy']["Porte d'Italie"] = 120.0
graph["Porte d'Italie"]['Porte de Choisy'] = 120.0
graph["Porte d'Italie"]['Maison Blanche'] = 60.0
graph['Avron']['Nation'] = 60.0
graph['Avron']['Alexandre Dumas'] = 60.0
graph['Alexandre Dumas']['Avron'] = 60.0
graph['Alexandre Dumas']['Philippe Auguste'] = 60.0
graph['Philippe Auguste']['Alexandre Dumas'] = 60.0
graph['Philippe Auguste']['Père Lachaise'] = 60.0
graph['Ménilmontant']['Père Lachaise'] = 60.0
graph['Ménilmontant']['Couronnes'] = 60.0
graph['Couronnes']['Ménilmontant'] = 60.0
graph['Couronnes']['Belleville'] = 60.0
graph['Belleville']['Couronnes'] = 60.0
graph['Belleville']['Colonel Fabien'] = 60.0
graph['Belleville']['Goncourt'] = 60.0
graph['Belleville']['Pyrénées'] = 60.0
graph['Colonel Fabien']['Belleville'] = 60.0
graph['Colonel Fabien']['Jaurès'] = 60.0
graph['La Chapelle']['Stalingrad'] = 60.0
graph['La Chapelle']['Barbès - Rochechouart'] = 60.0
graph['Barbès - Rochechouart']['La Chapelle'] = 60.0
graph['Barbès - Rochechouart']['Anvers'] = 60.0
graph['Barbès - Rochechouart']['Château Rouge'] = 60.0
graph['Barbès - Rochechouart']['Gare du Nord'] = 120.0
graph['Anvers']['Barbès - Rochechouart'] = 60.0
graph['Anvers']['Pigalle'] = 60.0
graph['Blanche']['Pigalle'] = 60.0
graph['Blanche']['Place de Clichy'] = 60.0
graph['Rome']['Place de Clichy'] = 60.0
graph['Rome']['Villiers'] = 60.0
graph['Monceau']['Villiers'] = 60.0
graph['Monceau']['Courcelles'] = 60.0
graph['Courcelles']['Monceau'] = 60.0
graph['Courcelles']['Ternes'] = 60.0
graph['Ternes']['Courcelles'] = 60.0
graph['Ternes']['Charles de Gaulle - Etoile'] = 60.0
graph['Victor Hugo']['Charles de Gaulle - Etoile'] = 60.0
graph['Victor Hugo']['Porte Dauphine'] = 60.0
graph['Porte Dauphine']['Victor Hugo'] = 60.0
graph['Bercy']['Gare de Lyon'] = 60.0
graph['Bercy']['Cour Saint-Emilion'] = 60.0
graph['Bercy']['Dugommier'] = 60.0
graph['Bercy']['Quai de la Gare'] = 60.0
graph['Cour Saint-Emilion']['Bercy'] = 60.0
graph['Cour Saint-Emilion']['Bibliothèque François Mitterrand'] = 60.0
graph['Bibliothèque François Mitterrand']['Cour Saint-Emilion'] = 60.0
graph['Bibliothèque François Mitterrand']['Olympiades'] = 60.0
graph['Olympiades']['Bibliothèque François Mitterrand'] = 60.0
graph['Pont Cardinet']['Saint-Lazare'] = 120.0
graph['Pont Cardinet']['Porte de Clichy'] = 60.0
graph['Saint-Ouen']['Porte de Clichy'] = 120.0
graph['Saint-Ouen']['Mairie de Saint-Ouen'] = 60.0
graph['Rambuteau']['Hôtel de Ville'] = 60.0
graph['Rambuteau']['Arts et Métiers'] = 60.0
graph['Goncourt']['République'] = 60.0
graph['Goncourt']['Belleville'] = 60.0
graph['Pyrénées']['Belleville'] = 60.0
graph['Pyrénées']['Jourdain'] = 60.0
graph['Jourdain']['Pyrénées'] = 60.0
graph['Jourdain']['Place des Fêtes'] = 60.0
graph['Télégraphe']['Place des Fêtes'] = 60.0
graph['Télégraphe']['Porte des Lilas'] = 60.0
graph['Mairie des Lilas']['Porte des Lilas'] = 60.0
graph['Maraîchers']['Porte de Montreuil'] = 60.0
graph['Maraîchers']['Buzenval'] = 60.0
graph['Buzenval']['Maraîchers'] = 60.0
graph['Buzenval']['Nation'] = 60.0
graph['Rue des Boulets']['Nation'] = 60.0
graph['Rue des Boulets']['Charonne'] = 60.0
graph['Charonne']['Rue des Boulets'] = 60.0
graph['Charonne']['Voltaire'] = 60.0
graph['Voltaire']['Charonne'] = 60.0
graph['Voltaire']['Saint-Ambroise'] = 60.0
graph['Saint-Ambroise']['Voltaire'] = 60.0
graph['Saint-Ambroise']['Oberkampf'] = 60.0
graph['Saint-Augustin']['Havre-Caumartin'] = 60.0
graph['Saint-Augustin']['Miromesnil'] = 60.0
graph['Saint-Philippe du Roule']['Miromesnil'] = 60.0
graph['Saint-Philippe du Roule']['Franklin D. Roosevelt'] = 60.0
graph['Alma - Marceau']['Franklin D. Roosevelt'] = 60.0
graph['Alma - Marceau']['Iéna'] = 60.0
graph['Iéna']['Alma - Marceau'] = 60.0
graph['Iéna']['Trocadéro'] = 60.0
graph['Rue de la Pompe']['Trocadéro'] = 60.0
graph['Rue de la Pompe']['La Muette'] = 60.0
graph['La Muette']['Rue de la Pompe'] = 60.0
graph['La Muette']['Ranelagh'] = 60.0
graph['Ranelagh']['La Muette'] = 60.0
graph['Ranelagh']['Jasmin'] = 60.0
graph['Jasmin']['Ranelagh'] = 60.0
graph['Jasmin']['Michel-Ange - Auteuil'] = 60.0
graph['Exelmans']['Michel-Ange - Molitor'] = 60.0
graph['Exelmans']['Porte de Saint-Cloud'] = 60.0
graph['Porte de Clignancourt']['Simplon'] = 60.0
graph['Simplon']['Porte de Clignancourt'] = 60.0
graph['Simplon']['Marcadet - Poissonniers'] = 60.0
graph['Château Rouge']['Marcadet - Poissonniers'] = 60.0
graph['Château Rouge']['Barbès - Rochechouart'] = 60.0
graph["Château d'Eau"]["Gare de l'Est"] = 60.0
graph["Château d'Eau"]['Strasbourg - Saint-Denis'] = 60.0
graph['Etienne Marcel']['Réaumur - Sébastopol'] = 60.0
graph['Etienne Marcel']['Les Halles'] = 60.0
graph['Les Halles']['Etienne Marcel'] = 60.0
graph['Les Halles']['Châtelet'] = 60.0
graph['Cité']['Châtelet'] = 60.0
graph['Cité']['Saint-Michel'] = 60.0
graph['Saint-Michel']['Cité'] = 60.0
graph['Saint-Michel']['Odéon'] = 60.0
graph['Saint-Germain-des-Prés']['Odéon'] = 60.0
graph['Saint-Germain-des-Prés']['Saint-Sulpice'] = 60.0
graph['Saint-Sulpice']['Saint-Germain-des-Prés'] = 60.0
graph['Saint-Sulpice']['Saint-Placide'] = 60.0
graph['Saint-Placide']['Saint-Sulpice'] = 60.0
graph['Saint-Placide']['Montparnasse Bienvenue'] = 60.0
graph['Vavin']['Montparnasse Bienvenue'] = 60.0
graph['Vavin']['Raspail'] = 60.0
graph['Mouton-Duvernet']['Denfert-Rochereau'] = 60.0
graph['Mouton-Duvernet']['Alésia'] = 60.0
graph['Alésia']['Mouton-Duvernet'] = 60.0
graph['Alésia']["Porte d'Orléans"] = 60.0
graph["Porte d'Orléans"]['Alésia'] = 60.0
graph["Porte d'Orléans"]['Mairie de Montrouge'] = 60.0
graph['Mairie de Montrouge']["Porte d'Orléans"] = 60.0
graph['Mairie de Montrouge']['Barbara'] = 120.0
graph['Barbara']['Mairie de Montrouge'] = 120.0
graph['Barbara']['Bagneux - Lucie Aubrac'] = 60.0
graph['Bagneux - Lucie Aubrac']['Barbara'] = 60.0
graph['Picpus']['Nation'] = 60.0
graph['Picpus']['Bel-Air'] = 60.0
graph['Bel-Air']['Picpus'] = 60.0
graph['Bel-Air']['Daumesnil'] = 60.0
graph['Dugommier']['Daumesnil'] = 60.0
graph['Dugommier']['Bercy'] = 60.0
graph['Quai de la Gare']['Bercy'] = 60.0
graph['Quai de la Gare']['Chevaleret'] = 60.0
graph['Chevaleret']['Quai de la Gare'] = 60.0
graph['Chevaleret']['Nationale'] = 60.0
graph['Nationale']['Chevaleret'] = 60.0
graph['Nationale']["Place d'Italie"] = 60.0
